# Generated by Django 4.1 on 2022-08-30 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, max_length=2048)),
                ("type", models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("desc", models.CharField(max_length=128)),
                ("tag", models.CharField(max_length=128)),
                (
                    "priority",
                    models.CharField(
                        choices=[("1", "Faible"), ("3", "Elevée"), ("2", "Moyenne")],
                        max_length=150,
                    ),
                ),
                ("status", models.CharField(max_length=128)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        blank="true",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(choices=[("allowed", "Autorisé")], max_length=150),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        blank="true",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2048)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "issue_id",
                    models.ForeignKey(
                        blank="true",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.issues",
                    ),
                ),
            ],
        ),
    ]
