# Generated by Django 4.1 on 2022-08-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_comments_author_user_id_contributors_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="priority",
            field=models.CharField(
                choices=[("2", "Moyenne"), ("3", "Elevée"), ("1", "Faible")],
                max_length=150,
            ),
        ),
    ]
