# Generated by Django 4.1 on 2022-09-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_issues_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issues",
            name="priority",
            field=models.CharField(
                choices=[("1", "Faible"), ("3", "Elevée"), ("2", "Moyenne")],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.TextField(max_length=2048),
        ),
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(max_length=128),
        ),
    ]
